### ISSUE TITLE
Reference JSON Parameters File

### ISSUE THREAD

**Issue by rfcomp** [aws-samples/aws-refarch-wordpress#33]
I am sorry to ask this here but I am not able to figure it out via my research.

How do you reference a parameter file such as https://github.com/awslabs/aws-refarch-wordpress/blob/master/samples/aws-refarch-wordpress-parameters-newvpc.json when you are creating a CloudFormation stack?

**Comment by darrylsosborne** [comment]
You pass the parameter file when creating a CloudFormation stack using the CLI.  A sample CLI command is below (along with a link to the file script).

https://github.com/awslabs/aws-refarch-wordpress/blob/master/samples/aws-refarch-wordpress-sample-cli-newvpc.sh

aws cloudformation create-stack \
 --stack-name WordPress \
 --template-body https://s3.amazonaws.com/aws-refarch/wordpress/latest/templates/aws-refarch-wordpress-master-newvpc.yaml \
 --parameters file://aws-refarch-wordpress-parameters-newvpc.json \
 --capabilities CAPABILITY_IAM \
 --disable-rollback \
 --region us-east-1 \
 --output json

**Comment by rfcomp** [comment]
Great! Thank you.
