### ISSUE TITLE
Stack fails if long resource IDs are enabled on the account

### ISSUE THREAD

**Issue by chriscasto** [aws-samples/aws-refarch-wordpress#36]
If long resource IDs are enabled on the account, the VPC created by this stack is given an ID that doesn't pass the validation regex in the subnet template, causing stack creation to fail.  This is a feature that can be manually enabled for now, but will automatically be turned on after June 2018.

https://aws.amazon.com/about-aws/whats-new/2018/02/longer-format-resource-ids-are-now-available-in-amazon-ec2/

**Comment by brianhull** [comment]
Why hasn't this been implemented? I need this code too. Thanks
